# ref : https://namileriblog.com/terminal/terminal_setting_starship/
# ref : https://tech-unlimited.com/color.html

format = """
[](fg:#7aa2f7 bg:#1e1f2a)\
$os\
[ ](fg:#7aa2f7 bg:#1e1f2a)\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$python\
[](fg:#1e1f2a)\
$fill\
$cmd_duration\
$time\
\n$character\
"""

# right_format = """
# $cmd_duration\
# $battery\
# $time\
# """

[os]
# format = "[$symbol](bold white)"
format = "[$symbol]($style)"
style = 'fg:#1e1f2a bg:#7aa2f7 bold white'
disabled = false
[os.symbols]
Macos = "  "  # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian

[hostname]
ssh_only = true
style = 'fg:#fe78c5 bg:#1e1f2a bold'
ssh_symbol = ' '
format = '[$ssh_symbol$hostname ]($style)'
disabled = false

[directory]
truncation_length = 100
truncation_symbol = ' ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = ' ~' # nf-fa-home
#style = 'fg:#7aa2f7 bg:#1a1b4d'
style = 'fg:#fe78c5 bg:#1e1f1a bold'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1e1f2a bold'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '  ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
#style = 'fg:#7aa2f7 bg:#1a1b4d'
style = 'fg:#fe78c5 bg:#1e1f2a bold'
format = '[ ❱ $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider
# format = '[ ❱ $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#ebaf68 bg:#1e1f2a bold'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
# stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a bg:#1e1f2a bold'
deleted_style = 'fg:#9ece6a bg:#1e1f2a bold'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[python]
symbol = '󰌠 '
style = 'fg:#f1fa8c bg:#1e1f2a bold'
format = '[ ❱ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[fill]
symbol = '─'
style = 'blue'

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[cmd_duration]
min_time = 1
style = 'fg:#ebaf68 bold'
format = "[ ❰  $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock
# format = "[ ❰  $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[battery]
# style = 'fg:#e0af68'
# style = "bold blue"
format = ' ❰ [$symbol$percentage]($style)'
# format = ' ❰ [$symbol$percentage]($style)'
[[battery.display]]
threshold = 100
style = "bold blue"

[time]
disabled = false
style = 'fg:#73daca bold'
format = '[ ❰  $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
# format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'
use_12hr = false
