#!/bin/bash

options=(
  style=round
  width=8.0
  hidpi=on
  # active_color=0xc0ff00f2
  # active_color="gradient(top_left=0xc0ff00f2,bottom_right=0xff00ff80)"
  active_color="glow(0xffff00f2)"
  inactive_color=0xff0080ff
)

borders "${options[@]}"
