# zabrze configuration: https://github.com/Ryooooooga/zabrze

snippets = [
  { trigger = "c",        snippet = "clear" },
  { trigger = "zc",       snippet = "z && clear" },
  { trigger = "e",        snippet = "exit" },
  { trigger = "sz",       snippet = "source ~/.zshrc" },
  { trigger = "ez",       snippet = "exec zsh" },
  { trigger = "DN",       snippet = "/dev/null",                  global = true },
  { trigger = "NE",       snippet = "2>/dev/null",                global = true },
  ### Path ###
  { trigger = "/d",       snippet = "~/Downloads/{}",             global = true },
  { trigger = "/dd",      snippet = "~/.dotfiles/{}",             global = true },
  { trigger = "/dc",      snippet = "~/.config/{}",               global = true },
  { trigger = "/dlb",     snippet = "~/.local/bin/{}",            global = true },
  { trigger = "/sh",      snippet = "~/Documents/ShellScript/{}", global = true },
  { trigger = "/cd",      snippet = "~/Music/CD/{}",              global = true },
  { trigger = "/meisai",  snippet = "/Volumes/SV-DT/明細/{}",     global = true },
  ### Neovim ###
  { trigger = "v",        snippet = "nvim",                       global = true },
  { trigger = "vb",       snippet = "nvim +" },
  { trigger = "vd",       snippet = "nvim -d" },
  { trigger = "vf",       snippet = "nvim $(fzf)" },
  { trigger = "vc",       snippet = "nvim ~/.dotfiles/nvim/lua/hamu/" },
  { trigger = "vz",       snippet = "nvim ~/.zshrc" },
  { trigger = "vo",       snippet = "nvim ~/Library/Mobile\\ Documents/iCloud~md~obsidian/Documents/ObsidianVault" },
  { trigger = "vt",       snippet = "nvim ~/Documents/temp.txt" },
  { trigger = "vcd",      snippet = "nvim ~/Music/CD" },
  { trigger = "vdw",      snippet = "nvim ~/Downloads" },
  { trigger = "vij",      snippet = "nvim ~/Music/伊集院光\\ 深夜の馬鹿力.cue" },
  { trigger = "vsh",      snippet = "nvim ~/Documents/ShellScript" },
  { trigger = "vzb",      snippet = "nvim ~/.dotfiles/zabrze/config.toml" },
  ### Homebrew ###
  { trigger = "bu",       snippet = "brew update && brew upgrade -y && brew cleanup" },
  { trigger = "bri",      snippet = "brew install" },
  { trigger = "brs",      snippet = "brew search" },
  { trigger = "bru",      snippet = "brew uninstall" },
  { trigger = "brf",      snippet = "brew info" },
  { trigger = "brc",      snippet = "brew cleanup" },
  { trigger = "b",        snippet = "brew",                       global = true },
  { trigger = "i",        snippet = "install",                    global = true, context = "^brew\\s" },
  { trigger = "s",        snippet = "search",                     global = true, context = "^brew\\s" },
  { trigger = "u",        snippet = "uninstall",                  global = true, context = "^brew\\s" },
  { trigger = "if",       snippet = "info",                       global = true, context = "^brew\\s" },
  { trigger = "c",        snippet = "cleanup",                    global = true, context = "^brew\\s" },
  { trigger = "d",        snippet = "doctor",                     global = true, context = "^brew\\s" },
  { trigger = "ls",       snippet = "list",                       global = true, context = "^brew\\s" },
  ### Zoxide ###
  { trigger = "cd",       snippet = "z",                          global = true },
  { trigger = "zd",       snippet = "z ~/.dotfiles" },
  ### EZA ###
  { trigger = "ls",       snippet = "eza",                        global = true },
  { trigger = "ll",       snippet = "eza -l" },
  { trigger = "lls",      snippet = "eza --total-size -l" },
  { trigger = "la",       snippet = "eza -la" },
  { trigger = "las",      snippet = "eza --total-size -la" },
  { trigger = "lsb",      snippet = "eza -la ~/.local/bin" },
  { trigger = "lst",      snippet = "eza -T --level={}" },
  { trigger = "lat",      snippet = "eza -la --total-size -T --level={}" },
  ### cp ###
  { trigger = "cp",       snippet = "cp -aiv" },
  { trigger = "cpm",      snippet = "cp -aiv {} & progress -mp $!" },
  ### mv ###
  { trigger = "mv",       snippet = "mv -iv" },
  { trigger = "mvm",      snippet = "mv -iv {} & progress -mp $!" },
  { trigger = "mkdir",    snippet = "mkdir -p" },
    ### Git ###
  { trigger = "g",        snippet = "git" },
  { trigger = "ga",       snippet = "git add" },
  { trigger = "gad",      snippet = "git add ." },
  { trigger = "gbr",      snippet = "git branch" },
  { trigger = "gcm",      snippet = "git commit -m \"{}\"" },
  { trigger = "gpl",      snippet = "git pull" },
  { trigger = "gps",      snippet = "git push" },
  { trigger = "gcl",      snippet = "git clone" },
  { trigger = "P",        snippet = "push",                       global = true, context = "^git\\s" },
  { trigger = "a",        snippet = "add",                        global = true, context = "^git\\s" },
  { trigger = "ad",       snippet = "add .",                      global = true, context = "^git\\s" },
  { trigger = "c",        snippet = "commit -m \"{}\"",           global = true, context = "^git\\s" },
  { trigger = "co",       snippet = "checkout",                   global = true, context = "^git\\s" },
  { trigger = "d",        snippet = "diff",                       global = true, context = "^git\\s" },
  { trigger = "f",        snippet = "fetch",                      global = true, context = "^git\\s" },
  { trigger = "l",        snippet = "log",                        global = true, context = "^git\\s" },
  { trigger = "p",        snippet = "pull",                       global = true, context = "^git\\s" },
  { trigger = "st",       snippet = "status",                     global = true, context = "^git\\s" },
  ### Lazygit ###
  { trigger = "lg",       snippet = "lazygit" },
  { trigger = "lgd",      snippet = "lazygit -p ~/.dotfiles" },
  ### Docker ###
  { trigger = "d",        snippet = "docker",                     global = true                         },
  { trigger = "cp",       snippet = "compose pull",               global = true, context = "^docker\\s" },
  { trigger = "cu",       snippet = "compose up -d",              global = true, context = "^docker\\s" },
  { trigger = "cuf",      snippet = "compose up -d",              global = true, context = "^docker\\s" },
  ### Tmux ###
  { trigger = "tm",       snippet = "tmux" },
  { trigger = "tma",      snippet = "tmux a" },
  ### Herdr ###
  { trigger = "hd",       snippet = "herdr" },
  { trigger = "hdr",      snippet = "herdr --remote" },
  ### XATTR ###
  { trigger = "xd",       snippet = "xattr -d com.apple.metadata:kMDItemWhereFroms" },
  { trigger = "xr",       snippet = "xattr -rc" },
  ### etc ###
  { trigger = "scp2d",    snippet = "scp {} @:~/Downloads" },
  { trigger = "7zx",      snippet = "7zz x" },
  { trigger = "bottom",   snippet = "btm" },
  { trigger = "fd",       snippet = "fd -H" },
  { trigger = "ff",       snippet = "fastfetch" },
  { trigger = "ln",       snippet = "ln -snvf" },
  { trigger = "rg",       snippet = "rg -i",                      global = true },
  { trigger = "grep",     snippet = "grep -i",                    global = true },
  { trigger = "trm",      snippet = "trash -v" },
  { trigger = "tty",      snippet = "tty-clock -c -C 4" },
  { trigger = "ttys",     snippet = "tty-clock -sc -C 4" },
  { trigger = "y",        snippet = "yazi" },
  { trigger = "zls",      snippet = "zabrze list" },
  { trigger = "zmv",      snippet = "zmv -W" },
  ### Command ###
  { trigger = "oc",       snippet = "fd -e cue --min-depth 2 . ~/Music/CD -X nvim" },
  { trigger = "ytdls",    snippet = "fd -H list ~/Movies/yt-dlp -X bat" },
  { trigger = "sfc",      snippet = "fd -e mp4 . /Volumes/SV-AV | fzf" },
  { trigger = "token",    snippet = "deno x npm:tokscale@latest" },
  { trigger = "mvtmr",    snippet = "mv -iv ~/Downloads/2026* /mnt/SV-VD/息根とめる/2026/ & progress -mp $!" },
  ### Mac OS ###
  { trigger = "C",        snippet = "| pbcopy",                   global = true },
  { trigger = "sleep",    snippet = "pmset sleepnow" },
  ### Ubuntu ###
  { trigger = "aptup",    snippet = "sudo apt update && sudo apt upgrade -y" },
  { trigger = "nlup",     snippet = "sudo nala update && sudo nala upgrade -y" },
  { trigger = "motd",     snippet = "run-parts /etc/update-motd.d/" },
  { trigger = "tls",      snippet = "trash-list" },
  { trigger = "tem",      snippet = "trash-empty" },
]
